#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot
unpack /filesystem/etc /etc

systemctl enable webcontrol.service

cd /home/"${BASE_USER}"
mkdir webcontrol
cd webcontrol
wget https://github.com/WebControlCNC/WebControl/releases/download/v0.9333/webcontrol-0.9333-rpi-singledirectory.tar.gz
tar -zxvf webcontrol-0.9333-rpi-singledirectory.tar.gz


# Unpack root at the end, so files are modified before
unpack /filesystem/root /
